# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qtui_for_geotasks_v-1.2.ui',
# licensing of 'Qtui_for_geotasks_v-1.2.ui' applies.
#
# Created: Wed Nov 20 14:30:20 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 410)
        MainWindow.setMinimumSize(QtCore.QSize(900, 410))
        MainWindow.setMaximumSize(QtCore.QSize(900, 413))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/mainwindow.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.button_ogz = QtWidgets.QPushButton(self.centralwidget)
        self.button_ogz.setMinimumSize(QtCore.QSize(145, 0))
        self.button_ogz.setMaximumSize(QtCore.QSize(145, 16777215))
        self.button_ogz.setCursor(QtCore.Qt.PointingHandCursor)
        self.button_ogz.setDefault(False)
        self.button_ogz.setFlat(False)
        self.button_ogz.setObjectName("button_ogz")
        self.gridLayout.addWidget(self.button_ogz, 0, 0, 1, 1)
        self.button_pgz = QtWidgets.QPushButton(self.centralwidget)
        self.button_pgz.setMinimumSize(QtCore.QSize(145, 0))
        self.button_pgz.setMaximumSize(QtCore.QSize(145, 16777215))
        self.button_pgz.setCursor(QtCore.Qt.PointingHandCursor)
        self.button_pgz.setObjectName("button_pgz")
        self.gridLayout.addWidget(self.button_pgz, 0, 1, 1, 1)
        self.button_square = QtWidgets.QPushButton(self.centralwidget)
        self.button_square.setMinimumSize(QtCore.QSize(145, 0))
        self.button_square.setMaximumSize(QtCore.QSize(145, 16777215))
        self.button_square.setCursor(QtCore.Qt.PointingHandCursor)
        self.button_square.setObjectName("button_square")
        self.gridLayout.addWidget(self.button_square, 0, 2, 1, 1)
        self.button_intersection = QtWidgets.QPushButton(self.centralwidget)
        self.button_intersection.setMinimumSize(QtCore.QSize(145, 0))
        self.button_intersection.setMaximumSize(QtCore.QSize(145, 16777215))
        self.button_intersection.setCursor(QtCore.Qt.PointingHandCursor)
        self.button_intersection.setObjectName("button_intersection")
        self.gridLayout.addWidget(self.button_intersection, 0, 3, 1, 1)
        self.button_clean = QtWidgets.QPushButton(self.centralwidget)
        self.button_clean.setCursor(QtCore.Qt.PointingHandCursor)
        self.button_clean.setObjectName("button_clean")
        self.gridLayout.addWidget(self.button_clean, 0, 4, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 0, 1, 5)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setMinimumSize(QtCore.QSize(620, 320))
        self.stackedWidget.setMaximumSize(QtCore.QSize(620, 320))
        self.stackedWidget.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.page.setObjectName("page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.page)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.ogz_lineedit_x1 = QtWidgets.QLineEdit(self.frame_2)
        self.ogz_lineedit_x1.setObjectName("ogz_lineedit_x1")
        self.gridLayout_3.addWidget(self.ogz_lineedit_x1, 0, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.frame_2)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.ogz_lineedit_y1 = QtWidgets.QLineEdit(self.frame_2)
        self.ogz_lineedit_y1.setObjectName("ogz_lineedit_y1")
        self.gridLayout_3.addWidget(self.ogz_lineedit_y1, 1, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame_2)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 1)
        self.ogz_lineedit_x2 = QtWidgets.QLineEdit(self.frame_2)
        self.ogz_lineedit_x2.setObjectName("ogz_lineedit_x2")
        self.gridLayout_3.addWidget(self.ogz_lineedit_x2, 2, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.frame_2)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 2, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 3, 0, 1, 1)
        self.ogz_lineedit_y2 = QtWidgets.QLineEdit(self.frame_2)
        self.ogz_lineedit_y2.setObjectName("ogz_lineedit_y2")
        self.gridLayout_3.addWidget(self.ogz_lineedit_y2, 3, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.frame_2)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 3, 2, 1, 1)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setMinimumSize(QtCore.QSize(300, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 2)
        self.ogz_button_submit = QtWidgets.QPushButton(self.frame)
        self.ogz_button_submit.setCursor(QtCore.Qt.PointingHandCursor)
        self.ogz_button_submit.setObjectName("ogz_button_submit")
        self.gridLayout_4.addWidget(self.ogz_button_submit, 1, 0, 1, 1)
        self.ogz_spinBox = QtWidgets.QSpinBox(self.frame)
        self.ogz_spinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ogz_spinBox.setMaximum(10)
        self.ogz_spinBox.setProperty("value", 2)
        self.ogz_spinBox.setObjectName("ogz_spinBox")
        self.gridLayout_4.addWidget(self.ogz_spinBox, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(self.page)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.ogz_label_answer = QtWidgets.QLabel(self.page)
        self.ogz_label_answer.setMaximumSize(QtCore.QSize(16777215, 25))
        self.ogz_label_answer.setWordWrap(False)
        self.ogz_label_answer.setObjectName("ogz_label_answer")
        self.verticalLayout_3.addWidget(self.ogz_label_answer)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.frame_9 = QtWidgets.QFrame(self.page_2)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.frame_9)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.pgz_lineedit_x = QtWidgets.QLineEdit(self.frame_9)
        self.pgz_lineedit_x.setInputMask("")
        self.pgz_lineedit_x.setText("")
        self.pgz_lineedit_x.setMaxLength(32767)
        self.pgz_lineedit_x.setCursorPosition(0)
        self.pgz_lineedit_x.setObjectName("pgz_lineedit_x")
        self.gridLayout_2.addWidget(self.pgz_lineedit_x, 0, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.frame_9)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_9)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.pgz_lineedit_y = QtWidgets.QLineEdit(self.frame_9)
        self.pgz_lineedit_y.setText("")
        self.pgz_lineedit_y.setObjectName("pgz_lineedit_y")
        self.gridLayout_2.addWidget(self.pgz_lineedit_y, 1, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.frame_9)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 1, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_9)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.pgz_lineedit_s = QtWidgets.QLineEdit(self.frame_9)
        self.pgz_lineedit_s.setText("")
        self.pgz_lineedit_s.setObjectName("pgz_lineedit_s")
        self.gridLayout_2.addWidget(self.pgz_lineedit_s, 2, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.frame_9)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 2, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_9)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 3, 0, 1, 1)
        self.pgz_lineedit_g = QtWidgets.QLineEdit(self.frame_9)
        self.pgz_lineedit_g.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pgz_lineedit_g.setObjectName("pgz_lineedit_g")
        self.gridLayout_2.addWidget(self.pgz_lineedit_g, 3, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.frame_9)
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 3, 2, 1, 1)
        self.horizontalLayout_24.addWidget(self.frame_9)
        self.frame_4 = QtWidgets.QFrame(self.page_2)
        self.frame_4.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pgz_button_submit = QtWidgets.QPushButton(self.frame_4)
        self.pgz_button_submit.setCursor(QtCore.Qt.PointingHandCursor)
        self.pgz_button_submit.setDefault(False)
        self.pgz_button_submit.setFlat(False)
        self.pgz_button_submit.setObjectName("pgz_button_submit")
        self.gridLayout_5.addWidget(self.pgz_button_submit, 1, 0, 1, 1)
        self.pgz_spinBox = QtWidgets.QSpinBox(self.frame_4)
        self.pgz_spinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pgz_spinBox.setMaximum(10)
        self.pgz_spinBox.setProperty("value", 2)
        self.pgz_spinBox.setObjectName("pgz_spinBox")
        self.gridLayout_5.addWidget(self.pgz_spinBox, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 2)
        self.horizontalLayout_24.addWidget(self.frame_4)
        self.verticalLayout_16.addLayout(self.horizontalLayout_24)
        self.line_8 = QtWidgets.QFrame(self.page_2)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_16.addWidget(self.line_8)
        self.pgz_label_answer = QtWidgets.QLabel(self.page_2)
        self.pgz_label_answer.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pgz_label_answer.setText("")
        self.pgz_label_answer.setObjectName("pgz_label_answer")
        self.verticalLayout_16.addWidget(self.pgz_label_answer)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.square_spinBox = QtWidgets.QSpinBox(self.page_3)
        self.square_spinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.square_spinBox.setMaximum(10)
        self.square_spinBox.setProperty("value", 2)
        self.square_spinBox.setObjectName("square_spinBox")
        self.gridLayout_6.addWidget(self.square_spinBox, 1, 4, 1, 1)
        self.square_textedit = QtWidgets.QTextEdit(self.page_3)
        self.square_textedit.setFrameShape(QtWidgets.QFrame.Box)
        self.square_textedit.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.square_textedit.setObjectName("square_textedit")
        self.gridLayout_6.addWidget(self.square_textedit, 0, 0, 1, 3)
        self.frame_3 = QtWidgets.QFrame(self.page_3)
        self.frame_3.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.gridLayout_6.addWidget(self.frame_3, 0, 3, 1, 2)
        self.square_button_submit = QtWidgets.QPushButton(self.page_3)
        self.square_button_submit.setMinimumSize(QtCore.QSize(0, 0))
        self.square_button_submit.setCursor(QtCore.Qt.PointingHandCursor)
        self.square_button_submit.setObjectName("square_button_submit")
        self.gridLayout_6.addWidget(self.square_button_submit, 1, 3, 1, 1)
        self.square_button_import = QtWidgets.QPushButton(self.page_3)
        self.square_button_import.setCursor(QtCore.Qt.PointingHandCursor)
        self.square_button_import.setObjectName("square_button_import")
        self.gridLayout_6.addWidget(self.square_button_import, 1, 0, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.line_11 = QtWidgets.QFrame(self.page_3)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout.addWidget(self.line_11)
        self.square_label_answer = QtWidgets.QLabel(self.page_3)
        self.square_label_answer.setMinimumSize(QtCore.QSize(0, 25))
        self.square_label_answer.setMaximumSize(QtCore.QSize(16777215, 25))
        self.square_label_answer.setText("")
        self.square_label_answer.setObjectName("square_label_answer")
        self.verticalLayout.addWidget(self.square_label_answer)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_10 = QtWidgets.QFrame(self.page_4)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_12 = QtWidgets.QLabel(self.frame_10)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 0, 0, 1, 1)
        self.intersection_lineedit_p1 = QtWidgets.QLineEdit(self.frame_10)
        self.intersection_lineedit_p1.setObjectName("intersection_lineedit_p1")
        self.gridLayout_7.addWidget(self.intersection_lineedit_p1, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_10)
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_10)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 1, 0, 1, 1)
        self.intersection_lineedit_p2 = QtWidgets.QLineEdit(self.frame_10)
        self.intersection_lineedit_p2.setObjectName("intersection_lineedit_p2")
        self.gridLayout_7.addWidget(self.intersection_lineedit_p2, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_10)
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 1, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_10)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 2, 0, 1, 1)
        self.intersection_lineedit_p3 = QtWidgets.QLineEdit(self.frame_10)
        self.intersection_lineedit_p3.setObjectName("intersection_lineedit_p3")
        self.gridLayout_7.addWidget(self.intersection_lineedit_p3, 2, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_10)
        self.label_18.setObjectName("label_18")
        self.gridLayout_7.addWidget(self.label_18, 2, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_10)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 3, 0, 1, 1)
        self.intersection_lineedit_p4 = QtWidgets.QLineEdit(self.frame_10)
        self.intersection_lineedit_p4.setObjectName("intersection_lineedit_p4")
        self.gridLayout_7.addWidget(self.intersection_lineedit_p4, 3, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_10)
        self.label_19.setObjectName("label_19")
        self.gridLayout_7.addWidget(self.label_19, 3, 2, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.page_4)
        self.frame_11.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_11.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.intersection_spinBox = QtWidgets.QSpinBox(self.frame_11)
        self.intersection_spinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.intersection_spinBox.setMaximum(10)
        self.intersection_spinBox.setProperty("value", 2)
        self.intersection_spinBox.setObjectName("intersection_spinBox")
        self.gridLayout_8.addWidget(self.intersection_spinBox, 2, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.frame_11)
        self.label_31.setWordWrap(True)
        self.label_31.setObjectName("label_31")
        self.gridLayout_8.addWidget(self.label_31, 0, 0, 1, 2)
        self.intersection_button_submit = QtWidgets.QPushButton(self.frame_11)
        self.intersection_button_submit.setCursor(QtCore.Qt.PointingHandCursor)
        self.intersection_button_submit.setObjectName("intersection_button_submit")
        self.gridLayout_8.addWidget(self.intersection_button_submit, 2, 0, 1, 1)
        self.intersection_button_plot = QtWidgets.QPushButton(self.frame_11)
        self.intersection_button_plot.setObjectName("intersection_button_plot")
        self.gridLayout_8.addWidget(self.intersection_button_plot, 3, 0, 1, 2)
        self.horizontalLayout_2.addWidget(self.frame_11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line_13 = QtWidgets.QFrame(self.page_4)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout_2.addWidget(self.line_13)
        self.intersection_label_answer = QtWidgets.QLabel(self.page_4)
        self.intersection_label_answer.setMinimumSize(QtCore.QSize(0, 25))
        self.intersection_label_answer.setMaximumSize(QtCore.QSize(16777215, 25))
        self.intersection_label_answer.setText("")
        self.intersection_label_answer.setObjectName("intersection_label_answer")
        self.verticalLayout_2.addWidget(self.intersection_label_answer)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_20 = QtWidgets.QLabel(self.page_5)
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_4.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.page_5)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_21.setObjectName("label_21")
        self.verticalLayout_4.addWidget(self.label_21)
        self.stackedWidget.addWidget(self.page_5)
        self.gridLayout.addWidget(self.stackedWidget, 2, 0, 2, 4)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 2, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.ogz_lineedit_x1, self.ogz_lineedit_y1)
        MainWindow.setTabOrder(self.ogz_lineedit_y1, self.ogz_lineedit_x2)
        MainWindow.setTabOrder(self.ogz_lineedit_x2, self.ogz_lineedit_y2)
        MainWindow.setTabOrder(self.ogz_lineedit_y2, self.ogz_spinBox)
        MainWindow.setTabOrder(self.ogz_spinBox, self.ogz_button_submit)
        MainWindow.setTabOrder(self.ogz_button_submit, self.pgz_lineedit_x)
        MainWindow.setTabOrder(self.pgz_lineedit_x, self.pgz_lineedit_y)
        MainWindow.setTabOrder(self.pgz_lineedit_y, self.pgz_lineedit_s)
        MainWindow.setTabOrder(self.pgz_lineedit_s, self.pgz_lineedit_g)
        MainWindow.setTabOrder(self.pgz_lineedit_g, self.pgz_spinBox)
        MainWindow.setTabOrder(self.pgz_spinBox, self.pgz_button_submit)
        MainWindow.setTabOrder(self.pgz_button_submit, self.square_button_import)
        MainWindow.setTabOrder(self.square_button_import, self.square_textedit)
        MainWindow.setTabOrder(self.square_textedit, self.square_spinBox)
        MainWindow.setTabOrder(self.square_spinBox, self.square_button_submit)
        MainWindow.setTabOrder(self.square_button_submit, self.intersection_lineedit_p1)
        MainWindow.setTabOrder(self.intersection_lineedit_p1, self.intersection_lineedit_p2)
        MainWindow.setTabOrder(self.intersection_lineedit_p2, self.intersection_lineedit_p3)
        MainWindow.setTabOrder(self.intersection_lineedit_p3, self.intersection_lineedit_p4)
        MainWindow.setTabOrder(self.intersection_lineedit_p4, self.intersection_spinBox)
        MainWindow.setTabOrder(self.intersection_spinBox, self.intersection_button_submit)
        MainWindow.setTabOrder(self.intersection_button_submit, self.button_ogz)
        MainWindow.setTabOrder(self.button_ogz, self.button_pgz)
        MainWindow.setTabOrder(self.button_pgz, self.button_square)
        MainWindow.setTabOrder(self.button_square, self.button_intersection)
        MainWindow.setTabOrder(self.button_intersection, self.button_clean)
        MainWindow.setTabOrder(self.button_clean, self.textEdit)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Калькулятор кадастрового инженера", None, -1))
        self.button_ogz.setText(QtWidgets.QApplication.translate("MainWindow", "ОГЗ", None, -1))
        self.button_pgz.setText(QtWidgets.QApplication.translate("MainWindow", "ПГЗ", None, -1))
        self.button_square.setText(QtWidgets.QApplication.translate("MainWindow", "Площадь полигона", None, -1))
        self.button_intersection.setText(QtWidgets.QApplication.translate("MainWindow", "Точка пересечения", None, -1))
        self.button_clean.setText(QtWidgets.QApplication.translate("MainWindow", "Очистить лог", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "X1=", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("MainWindow", "м", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Y1=", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("MainWindow", "м", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "X2=", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("MainWindow", "м", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Y2=", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("MainWindow", "м", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">Для вычисления дирекционного угла и горизонтального проложения линии АВ введите координаты точек А и В</p></body></html>", None, -1))
        self.ogz_button_submit.setText(QtWidgets.QApplication.translate("MainWindow", "Вычислить", None, -1))
        self.ogz_label_answer.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "X=", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("MainWindow", "м", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "Y=", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("MainWindow", "м", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "S=", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("MainWindow", "м", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "α=", None, -1))
        self.pgz_lineedit_g.setInputMask(QtWidgets.QApplication.translate("MainWindow", "000°00\'00\"", None, -1))
        self.pgz_lineedit_g.setText(QtWidgets.QApplication.translate("MainWindow", "°\'\"", None, -1))
        self.pgz_button_submit.setText(QtWidgets.QApplication.translate("MainWindow", "Вычислить", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">Для вычисления координат точки В введите координаты точки А, горизонтальное проложение и дирекционный угол линии АВ в градусах, минутах и секундах</p></body></html>", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">Для вычисления площади полигона введите координаты его вершин (X и Y вводятся через пробел, точки - с новой строки )</p></body></html>", None, -1))
        self.square_button_submit.setText(QtWidgets.QApplication.translate("MainWindow", "Вычислить", None, -1))
        self.square_button_import.setText(QtWidgets.QApplication.translate("MainWindow", "Импорт", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "P1(x,y)=", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "м", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "P2(x,y)=", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "м", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "P3(x,y)=", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("MainWindow", "м", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "P4(x,y)=", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "м", None, -1))
        self.label_31.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">Для вычисления координат точки пересечения двух отрезков введите координаты их концов </p></body></html>", None, -1))
        self.intersection_button_submit.setText(QtWidgets.QApplication.translate("MainWindow", "Вычислить", None, -1))
        self.intersection_button_plot.setText(QtWidgets.QApplication.translate("MainWindow", "График", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Программа-калькулятор для решения геодезических задач</span></p></body></html>", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">ГУЗ 2019</span></p></body></html>", None, -1))

import src_rc
